# Generated by Django 4.0 on 2021-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='helmet-1.jpg', null=True, upload_to='photos'),
        ),
    ]
