# Generated by Django 4.0 on 2021-12-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='helmet-1.png', null=True, upload_to='photos'),
        ),
    ]
